package com.componentes;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import javax.swing.Timer;

public class JClock extends javax.swing.JPanel implements ActionListener{

    private Timer timer = new Timer(1000,this);    
    
    public JClock() {
        initComponents();  
         timer.start();
    }
    
      public void actionPerformed(ActionEvent e) {
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");         
        lblClock.setText(sdf.format(new java.util.Date()));
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClock = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(137, 25));
        setLayout(null);

        lblClock.setText("jLabel1");
        add(lblClock);
        lblClock.setBounds(10, 0, 120, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblClock;
    // End of variables declaration//GEN-END:variables


  
}
